# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e9617c0ea58e3e3b2492f61390eb4a6585ffe88d216671211bed530caa8e2971ad8f34e66baa8684014387dfc7898c71f9b44202054db4f0e2120c3bb2fab4

test:
  secret_key_base: 5e10b9384db12f4921313245806ddfb4cd9bed2ed6b51a1f46aed211f550f82b4d18d59b21871eedd43c397d9eb3ad9a5f5db6fbe816a542bb0ae07a6baef5af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
